name = "DataEncryptionStandard"
uuid = "132ea8bf-b436-40fe-a200-f8d5376505c3"
authors = ["bouddhaacelee <bouddhaacelee@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
